language: rust
cache: cargo
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --package net --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
