language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --package http --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
    - os: osx
