[package]
name = "http"
version = "0.0.3"
authors = ["Garrett Hartshaw <ghartshaw@gmail.com>"]
repository = "https://github.com/krsnik02/rust-http2.git"
readme = "README.md"
license = "MIT"

[dependencies]
log = "0.3.2"
mio = "0.4.1"
