[package]
name = "http-server"
version = "0.0.2"
authors = ["Garrett Hartshaw <ghartshaw@gmail.com>"]

[dependencies]
log = "0.3.2"
env_logger = "0.3.1"

[dependencies.net]
path = "net"
version = "0.0.2"
